project:
  type: website
  output-dir: "../website"

## Overall settings
website:
  title: "Machine Learning and Amazon Retail Data"
  navbar:
    search: true
    pinned: true
    # right:
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - intro.qmd
      - data.qmd
      - section: "Models and Methods"
        contents: models/*
      - conclusions.qmd
  repo-url: "https://github.com/CUBoulder-DS/5301-5000-Final-Report"
  page-navigation: true

bibliography: references.bib
# nocite: |
#   @*

## Controls for each output format
format:
  html:
    theme:
      - quartz
      - custom.scss
    page-layout: full
    smooth-scroll: true
    number-sections: false
    citations-hover: true
    grid:
      body-width: 1000px
      sidebar-width: 150px
    quarto-required: ">= 1.4.0" # To fix crossrefs
  # pdf:
  #   quarto-required: ">= 1.4.0"
  #   documentclass: scrreprt
  #   number-sections: true
  #   number-depth: 4
  #   toc: true
  #   geometry:
  #     - margin=0.5in
  #   link-citations: true
  #   header-includes: # dont need?
  #     - \usepackage{float}
  #     - \usepackage{booktabs, caption, longtable, colortbl, array} # To make gt package work
  #     - \floatplacement{table}{H}
  #     - \floatplacement{image}{H}
  #   hyperrefoptions:
  #     - linktoc=all
  #   latex-output-dir: "../docs"

## Extra settings
execute:
  echo: false # Don't include code in the report
  freeze: false # Not useful when rendering across multiple users
  warning: false
  error: false

## PDF creation settings
latex-clean: true # delete latex files after rendering
latex-auto-mk: true
latex-auto-install: true
